### ISSUE TITLE
Need to be able to view user roles in mmctl

### ISSUE THREAD

**Issue by coderpilot** [mattermost/mmctl#558] opened 2022-10-03 16:06 UTC
A great auditing feature would be for admins to be able to use mmctl to request roles for all users.  This would be helpful in determining things like users with elevated privs that may no longer require it etc.  A discussion was started in this MM thread.

https://community.mattermost.com/core/pl/k1utfficqpg9dk44bsb4dkyhkr

@mkraft suggested the following

List all users

Usage:
  mmctl user list [flags]

Examples:
  user list

Flags:
      --all            Fetch all users. --page flag will be ignore if provided
  -h, --help           help for list
      --page int       Page number to fetch for the list of users
      --per-page int   Number of users to be fetched (default 200)
      --team string    If supplied, only users belonging to this team will be listed
+     --role string    Filter the results to users with the given role

I would even like a -r --roles flag with no params to simply include the role of the user in the output.

pq

**Comment by nobodygottimeforthat** [comment] 2022-10-04 14:19
Hi, is this issue still open and without any assignees?

I would like to solve it

**Comment by isacikgoz** [comment] 2022-10-31 16:28
Hey @nobodygottimeforthat it seems like the issue is assigned to someone else. I'll let you know how it goes.

**Comment by hanzei** [comment] 2024-01-22 11:41
Tracked via https://github.com/mattermost/mattermost/issues/21197

**Closed by hanzei** 2024-01-22 11:41 UTC
